Cherry pick of b66f7f2ee9bbcf0f8d83cd7a9415d84f041e3b8e failed
stdout:
Auto-merging content/administration/install/geo_ip.rst
CONFLICT (content): Merge conflict in content/administration/install/geo_ip.rst
CONFLICT (rename/delete): content/applications/websites/website/configuration/on-premise_geo-ip-installation/on-premise_geo-ip-installation01.png renamed to content/administration/install/geo_ip/on-premise_geo-ip-installation01.png in b66f7f2ee ([MOV] geo ip installation: move page to install), but deleted in HEAD.

stderr:
17:45:50.087762 git.c:463               trace: built-in: git cherry-pick b66f7f2ee9bbcf0f8d83cd7a9415d84f041e3b8e
error: could not apply b66f7f2ee... [MOV] geo ip installation: move page to install
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: